explicacao ta anotado no fichario

In [59]:
import numpy as np
#Adicionar anotacoes no Obsidian

O **Método dos Mínimos Quadrados** é uma técnica de aproximação numérica que encontra a curva polinomial que **melhor se ajusta** a um conjunto de pontos, minimizando a soma dos quadrados dos resíduos (diferenças entre os valores observados e os valores estimados pelo modelo).

---

$$P(x) = a_g x^g + a_{g-1} x^{g-1} + \cdots + a_1 x + a_0$$

tal que a soma seja mínima.

 $$S =  \frac{1}{2} \sum_{i=1}^{n} [y_i - P(x_i)]^2$$


In [60]:
#condicoes de contorno
dados = np.array([[1,6], [2,12], [3,20]])
display(dados)

#graus de polinomio
g = 2

array([[ 1,  6],
       [ 2, 12],
       [ 3, 20]])

### Método nao generico

In [61]:
#maneira generica de pegar os dados
#generico = dados[linhas, colunas]
#generico = dados[:,0] #slicing para pegar a primeira coluna ( : = todas as linhas, 0 = primeira coluna)
#generico = dados[:,1] #slicing para pegar a segunda coluna ( : = todas as linhas, 1 = segunda coluna)


x = dados[:,0] #slicing para pegar a primeira coluna
y = dados[:,1] #slicing para pegar a segunda coluna
display(x)
display(y)

array([1, 2, 3])

array([ 6, 12, 20])

## Calculando as Somatórias (Lado Esquerdo do Sistema)

Para um polinômio de grau 2, o sistema normal do MMQ tem a forma:

$$
\begin{bmatrix}
\sum x^4 & \sum x^3 & \sum x^2 \\
\sum x^3 & \sum x^2 & \sum x^1 \\
\sum x^2 & \sum x^1 & \sum x^0
\end{bmatrix}
\begin{bmatrix} a_2 \\ a_1 \\ a_0 \end{bmatrix}
=
\begin{bmatrix}
\sum x^2 y \\
\sum x^1 y \\
\sum x^0 y
\end{bmatrix}
$$

Calculamos primeiro as somatórias das potências de $x$, que formam a **matriz de equações** (lado esquerdo).

In [62]:
#range(start, end, step)
#print(list(range(2 * g, -1, -1)))

lista_potencias = []

for i in range(2 * g, -1, -1):
    print(((x ** i).sum()))
    lista_potencias.append((x ** i).sum())

98
36
14
6
3


In [63]:
matriz_esquerda = np.zeros(shape = (g + 1, g + 1), dtype = np.float64)
for i in range(0, g + 1, 1):
    j = g + 1 + i
    trecho = lista_potencias[i:j]
    matriz_esquerda[i] = trecho
display(matriz_esquerda)

array([[98., 36., 14.],
       [36., 14.,  6.],
       [14.,  6.,  3.]])

## Construindo a matriz direita

O vetor $D$ tem $(g+1)$ entradas, onde a $i$-ésima entrada é $\sum x^{g-i} y$.

O loop percorre `i` de `g` até `0` (decrescente), calculando cada somatória cruzada.

In [64]:
matriz_direita = np.zeros(shape = (g + 1, 1), dtype = np.float64)
for i in range(g, -1, -1):
    trecho_x = x ** i
    trecho_y = y
    print((trecho_x * trecho_y).sum())
    matriz_direita[g - i] = (trecho_x * trecho_y).sum()
display(matriz_direita)


234
90
38


array([[234.],
       [ 90.],
       [ 38.]])

In [66]:
coeficientes = np.linalg.solve(matriz_esquerda, matriz_direita)
display(coeficientes)

array([[1.],
       [3.],
       [2.]])

In [68]:
#funcao pronta

def mmq(dados: np.ndarray, g: int) -> np.ndarray:

    if not isinstance(dados, np.ndarray):
        raise TypeError("o parametro 'dados' deve ser um array")

    if not isinstance(g, int):
        raise TypeError("o parametro 'g' deve ser um int")
    
    x = dados[:, 0] # slice (fatiamento) do array
    y = dados[:, 1]

    lista_potencias = []
    for i in range(2 * g, -1, -1):
        lista_potencias.append((x ** i).sum())

    matriz_e = np.zeros(shape=(g+1, g+1), dtype=np.float64)
    for i in range(0, g + 1, 1):
        j = g + 1 + i
        trecho = lista_potencias[i:j]
        matriz_e[i] = trecho
    
    matriz_d = np.zeros(shape=(g+1, 1), dtype=np.float64)
    for i in range(g, -1, -1):
        trecho_x = x ** i
        trecho_y = y
        matriz_d[g-i] = (trecho_x * trecho_y).sum()
    
    coeficientes = np.linalg.solve(matriz_e, matriz_d)
    return coeficientes

In [70]:
print(mmq(dados, g=2))

[[1.]
 [3.]
 [2.]]


In [71]:
PRESETS = {
    "Ex. 1": [(1, 3), (2, 8), (3, 1), (4, 12), (5, 2), (6, 10), (7, 5), (8, 11), (9, 4)],
    "Ex. 2": [(1, 2),  (2, 10), (3, 30), (4, 68)],
    "Ex. 3": [(1, 3),  (2, 5),  (3, 7),  (4, 9),  (5, 11)],
}


In [76]:
print(mmq(dados=np.array(PRESETS["Ex. 1"]), g=3))
print(mmq(dados=np.array(PRESETS["Ex. 1"]), g=4))
print(mmq(dados=np.array(PRESETS["Ex. 1"]), g=5))

[[-0.03451178]
 [ 0.37373737]
 [-0.42508418]
 [ 4.27777778]]
[[-0.03875291]
 [ 0.74054649]
 [-4.80254468]
 [12.58482258]
 [-5.22222222]]
[[-0.0099359 ]
 [ 0.20964452]
 [-1.53918998]
 [ 4.55375874]
 [-3.93747086]
 [ 4.25      ]]
